services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks
    networks:
      - caddy_net
networks:
  caddy_net:
    external: true
